name: Docker Image CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        export TAG=${GITHUB_REF_NAME}_${GITHUB_RUN_NUMBER}
        docker build . --file Dockerfile --tag qgis-server:$TAG
