name: Docker Image CI

on:
  push:
    branches: [ "master", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Display image tag
      run: |
        export TAG=$env:GITHUB_REF_NAME_$env:GITHUB_RUN_NUMBER
        echo $TAG
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag qgis-server:$TAG
